version: '3.8'
services:
  app:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./:/usr/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: ssp_frontend
